### ISSUE TITLE
Veteran Kerbals become homesick even if the setting is off.

### ISSUE THREAD

**Issue by Eskandare** [UmbraSpaceIndustries/USI-LS#238] opened 2017-03-21 22:08 UTC
While adjusting the settings for the Veteran Kerbals, I discovered they will still become homesick with the setting off.

**Comment by snoopydude48** [comment] 2017-04-08 15:13
I am having the same issue.  Sent Bill on a trip to Minmus and he got homesick and turned into a tourist.  Here are my settings.

LIFE_SUPPORT_SETTINGS
{
	SupplyTime = 324000			//How many seconds before Kerbals are affected by no supplies
	ECTime = 324000				//How many seconds before Kerbals are affected by no EC
	EVATime = 21600				//How many seconds before ill effects on EVA
	ECAmount = 0.01				//EC per Kerbal per second						
	SupplyAmount = 0.0005		//Supplies consumed per Kerbal per second
	WasteAmount = 0.0005		//Mulch produced per Kerbal per second
	NoSupplyEffect = 1			//Effect if a Kerbal has no supplies
	NoSupplyEffectVets = 0		//Effect if a Kerbal is a vet and has no supplies
	NoECEffect = 1				//Effect if a Kerbal has no EC
	NoECEffectVets = 0			//Effect if a Kerbal is a vet and has no EC
	EVAEffect = 1				//Effect if a Kerbal exceeds EVA time		
	EVAEffectVets = 0			//Effect if a Kerbal is a vet and exceeds EVA time
	NoHomeEffect = 0			//Effect if a Kerbal becomes homesick
	NoHomeEffectVets = 0		//Effect if a Kerbal is a vet and becomes homesick
	HabMultiplier = 1			//Bonus to hab values (1 = default = 100% of the part's rated value)
	HomeWorldAltitude = 25000	//Altitude on Kerbin that negative effects are removed
	BaseHabTime = 1				//How long can 1 crew capacity support 1 Kerbal, expressed in Kerbal Months
	ReplacementPartAmount = 0	//How fast life support equipment and habs 'wears out'
	HabRange = 150				//How close we need to be to use other vessel's habitation modules and recyclers.
	EnableRecyclers = true		//Use resource recyclers?  Not the same as resource converteres like greenhouses!
	VetNames = Jebediah,Valentina,Bill,Bob	
	ScoutHabTime = 9180000
	PermaHabTime = 459000000

**Comment by theRagingIrishman** [comment] 2017-04-26 22:09
Changing the settings file won't affect current games. To affect current games you need to use the USI-LS gui in the space center view.

**Comment by BobPalmer** [comment] 2017-06-24 17:57
Closing as this is not a bug

**Closed by BobPalmer** 2017-06-24 17:57 UTC
